const data = [
    {
        id: 1,
        Question: [
            {
                id: 1,
                content: "Middle Era Name",
                hint1: "lithic",
                hint2: 'First part is "middle" in greek',
                correct_answer: "Mesolithic",
                answers: "*Last question*",
                type: "1",
            },
            {
                id: 2,
                content: "animal to hunt in the Stone Age",
                hint1: "Close to Rivers",
                hint2: "",
                correct_answer: "Fish",
                answers: "",
                type: "1",
            },
            {
                id: 3,
                content: "Rocks,Charcoal,Animal Fat",
                hint1: "Bring Paintings to life",
                hint2: "Artistic",
                correct_answer: "Paint, Colors",
                answers: "",
                type: "1",
            },
            {
                id: 4,
                content: "This Material Can be found on beaches",
                hint1: "Used to make Jewelery",
                hint2: "",
                correct_answer: "Shells",
                answers: "",
                type: "1",
            },
            {
                id: 5,
                content: "Living Creatures",
                hint1: "Died Befor Human Existance",
                hint2: "Fossils",
                correct_answer: "Dinosaurs",
                answers: "",
                type: "1",
            },
        ],
        name: "Stone Age",
        Period: "2.6 million years ago",
    },
    {
        id: 2,
        Question: [
            {
                id: 6,
                content: "War, Europe",
                hint1: "deadliest global conflicts in history",
                hint2: "",
                correct_answer: "World war",
                answers: "",
                type: "1",
            },
            {
                id: 7,
                content: "Football",
                hint1: "Countries",
                hint2: "",
                correct_answer: "World Cup",
                answers: "",
                type: "1",
            },
            {
                id: 8,
                content: "cough cough",
                hint1: "Wear Masks",
                hint2: "",
                correct_answer: "Covid",
                answers: "",
                type: "1",
            },
            {
                id: 9,
                content: "Space Discovery",
                hint1: "Person",
                hint2: "First one that did it",
                correct_answer: "Neil Armstrong",
                answers: "",
                type: "1",
            },
            {
                id: 10,
                content: "I wasted My money",
                hint1: "Meme Coin",
                hint2: "To the Moon 🚀",
                correct_answer: "Cryptocurrency",
                answers: "",
                type: "1",
            },
        ],
        name: "The modern era",
        Period: "1946 - present",
    },
    {
        id: 3,
        Question: [
            {
                id: 11,
                content: "Education",
                hint1: "Higher Studies",
                hint2: "",
                correct_answer: "university",
                answers: "",
                type: "1",
            },
            {
                id: 12,
                content: "Strong Kindoom in Eu",
                hint1: "800",
                hint2: "King",
                correct_answer: "Charlemagne",
                answers: "",
                type: "1",
            },
            {
                id: 13,
                content: "Europe capture",
                hint1: "Colonized",
                hint2: "alquds",
                correct_answer: "Jerusalem",
                answers: "",
                type: "1",
            },
            {
                id: 14,
                content: "Wearing Chain Body and Chest Plate",
                hint1: "Sword and Shield",
                hint2: "Time Period",
                correct_answer: "Medieval",
                answers: "",
                type: "1",
            },
        ],
        name: "Middle ages",
        Period: "400 - 1400",
    },
    {
        id: 4,
        Question: [
            {
                id: 15,
                content: "War",
                hint1: "Jewish",
                hint2: "extremenation camp",
                correct_answer: "Holocaust",
                answers: "",
                type: "1",
            },
            {
                id: 16,
                content: "War",
                hint1: "assasination",
                hint2: "archiduc",
                correct_answer: "word war 1 ",
                answers: "",
                type: "1",
            },
            {
                id: 17,
                content: "War",
                hint1: "naval base",
                hint2: "kamikazi",
                correct_answer: "Attack on Pearl Harbor",
                answers: "",
                type: "1",
            },
            {
                id: 18,
                content: "War",
                hint1: "nuclear bomb",
                hint2: "japan",
                correct_answer: "hiroshima atack",
                answers: "",
                type: "1",
            },
        ],
        name: "World Wars",
        Period: "1914 - 1945",
    },
    {
        id: 5,
        Question: [
            {
                id: 19,
                content: "travel",
                hint1: "Mekkah",
                hint2: "Maddinah",
                correct_answer: "Hijra",
                answers: "",
                type: "1",
            },
            {
                id: 20,
                content: "Islamic",
                hint1: "jewish",
                hint2: "forts ",

                correct_answer: "Battle of Khaybar",
                answers: "",
                type: "1",
            },
            {
                id: 21,
                content: "islam",
                hint1: "Army",
                hint2: "without blood",
                correct_answer: "Fath mekkah",
                answers: "",
                type: "1",
            },
            {
                id: 22,
                content: "mountain",
                hint1: "Khaled ibn walid",
                hint2: "arrows",
                correct_answer: "Battle of Auhod",
                answers: "",
                type: "1",
            },
        ],
        name: "Islamic Ira",
        Period: " 622 -...",
    },
    {
        id: 6,
        Question: [
            {
                id: 23,
                content: "ottoman",
                hint1: "1516",
                hint2: "ALgeria",
                correct_answer: "Capture of Algiers",
                answers: "",
                type: "1",
            },
            {
                id: 24,
                content: "َArmy",
                hint1: "ottoman",
                hint2: "َ elite corps",

                correct_answer: "Janissary",
                answers: "",
                type: "1",
            },
            {
                id: 25,
                content: "fall",
                hint1: "Turkey",
                hint2: "1923",
                correct_answer: "fall of ottoman empire",
                answers: "",
                type: "1",
            },
            {
                id: 26,
                content: "war",
                hint1: "Istanbul",
                hint2: "Mehmed",
                correct_answer: "Fall of Constantinople",
                answers: "",
                type: "1",
            },
        ],
        name: "othmani ira",
        Period: " 1299 -1923",
    },
];

export default data;
